name: PrisonNet
version: 1.0.0
api-version: 1.13
main: com.prison.net.Main
author: Bahzinga

commands:
  pickaxe:
    description: Manage pickaxes
    permission: prisonnet.pickaxe
  skins:
    description: Manage skins
    permission: prisonnet.skins